---
title: "20260430_a2d1_rnaseq_GOanalysis"
author: "G Sejourne"
date: "2026-04-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(clusterProfiler)
library(biomaRt)
library(org.Mm.eg.db)
library(enrichplot)
library(fgsea)
library(msigdbr)
library(VennDetail)
library(VennDiagram)
library(EnhancedVolcano)
library(apeglm)
library(readxl)
library(gplots)
library(pheatmap)
library(viridis)
library(dplyr)
library(ggplot2)
library(tidyr)

```

## GO analysis for bulk RNA sequencing

This code is for performing Gene Ontology analysis given lists of differentially expressed genes from pairwise comparison (Wald test) of bulk RNA sequencing. 

```{r}
plots_dir <- "plots"

if (!dir.exists(plots_dir)) {
  dir.create(plots_dir)
} else {
  print("Directory already exists!")
}

tables_dir <- "tables"

if (!dir.exists(tables_dir)) {
  dir.create(tables_dir)
} else {
  print("Directory already exists!")
}
```

```{r read in data}
res <- read.csv("./tables/a2d1_KOvsWT_results_sig.csv")
resSig <- subset(res, log2FoldChange < -log(1.25, 2) | log2FoldChange > log(1.25, 2))
```

## Including Plots

You can also embed plots, for example:

```{r GO biological process}
sig_up <- subset(resSig, log2FoldChange > 0)
sig_down <- subset(resSig, log2FoldChange < 0)

sig_up_genes <- sig_up$X
length(sig_up_genes)
sig_down_genes <- sig_down$X

length(sig_down_genes)
sig_diff_genes <- c(sig_up_genes, sig_down_genes)
```


```{r GO biological process for differentially expressed (up + down)}
# Run GO enrichment using SYMBOL
go_bp <- enrichGO(
  gene = sig_diff_genes,
  OrgDb = org.Mm.eg.db,
  keyType = "SYMBOL",
  universe = res$X,
  ont = "BP",
  readable = TRUE
)
head(go_bp)

library(enrichplot)
png("./plots/WTvKO_GO_BP.png", width=2000, height=2000, res=300)
  enrichplot::dotplot(go_bp, showCategory=15)
dev.off()


#save go output

write.csv(go_bp, file = "./tables/a2d1_genes_diff_GOBP.csv")
```

```{r GO biological process for upregulated genes}
# Run GO enrichment using SYMBOL
go_bp_up <- enrichGO(
  gene = sig_up_genes,
  OrgDb = org.Mm.eg.db,
  keyType = "SYMBOL",
  universe = res$X,
  ont = "BP",
  readable = TRUE
)
head(go_bp_up)

library(enrichplot)
png("./plots/WTvKO_GO_BP_UP.png", width=2000, height=2000, res=300)
  enrichplot::dotplot(go_bp_up, showCategory=10)
dev.off()


#save go output

write.csv(go_bp_up, file = "./tables/a2d1_genes_up_GOBP.csv")
```


```{r GO biological process for downregulated genes}
# Run GO enrichment using SYMBOL
go_bp_down <- enrichGO(
  gene = sig_down_genes,
  OrgDb = org.Mm.eg.db,
  keyType = "SYMBOL",
  universe = res$X,
  ont = "BP",
  readable = TRUE
)
head(go_bp_down)

library(enrichplot)
png("./plots/WTvKO_GO_BP_DOWN.png", width=2000, height=2000, res=300)
  enrichplot::dotplot(go_bp_down, showCategory=10)
dev.off()


#save go output

write.csv(go_bp_down, file = "./tables/a2d1_genes_down_GOBP.csv")
```

```{r}
#heatmap settings
myheatcol <- grDevices::colorRampPalette(c("lightblue","white", "orange"))(256)

dds <- readRDS("deseq_results_a2d1.rds")
vsd <- vst(dds, blind=FALSE)

df <- as.data.frame(colData(dds)) 
df <- df %>% arrange(Genotype)

# select lipid transport genes
lipidxport <- strsplit(go_bp[go_bp$Description == "lipid transport",]$geneID, "/")[[1]]

toPlot_lipidxport <- vsd[rownames(vsd) %in% lipidxport,]
toPlot_lipidxport <- toPlot_lipidxport[,rownames(df)]

#set quantile break points <https://slowkow.com/notes/pheatmap-tutorial/>
quantile_breaks <- function(xs, n = 100) {
  breaks <- quantile(xs, probs = seq(0, 1, length.out = n))
  breaks[!duplicated(breaks)]
}
toPlot_lipidxport_breaks <- quantile_breaks(assay(toPlot_lipidxport)[,1], n = 101)

mt <- toPlot_lipidxport[rownames(toPlot_lipidxport) %in% sig_diff_genes,]
# Labels to plot
    labels <- rownames(mt)
```


```{r}
# Open a PNG device with a transparent background
ppi <- 300
png(file = "./plots/heatmap_lipidxport_by_sample.png", width = 6*ppi, height = 6*ppi, res = ppi, bg = "transparent")

heatmap_lipid <- pheatmap(assay(mt), 
                          cluster_rows=TRUE, 
                          cluster_cols=FALSE,
                          show_colnames = FALSE,
                          #show_rownames = FALSE,
                          annotation_col=df[c(2)], 
                          scale = "row", 
                          fontsize_row = 10, 
                          fontsize_col = 10, 
                          color = myheatcol,
                          #color = viridis(length(toPlot_devmt_breaks)),
                          #breaks = toPlot_lipidxport_breaks, 
                          angle_col = 315, 
                          main = "Lipid transport genes", 
                          cellheight = 10, cellwidth = 10,
                          labels_row = labels, 
                          #cutree_rows = 2,
                          gaps_col = c(8, 16))

dev.off()
heatmap_lipid

```
```{r}
#heatmap settings
myheatcol <- grDevices::colorRampPalette(c("lightblue","white", "orange"))(256)


df <- as.data.frame(colData(dds)) 
df <- df %>% arrange(Genotype)

# select carboxylic acid biosynthetic process genes
cooh <- strsplit(go_bp[go_bp$Description == "carboxylic acid biosynthetic process",]$geneID, "/")[[1]]

toPlot_cooh <- vsd[rownames(vsd) %in% cooh,] 
toPlot_cooh <- toPlot_cooh[,rownames(df)]


#set quantile break points <https://slowkow.com/notes/pheatmap-tutorial/>
quantile_breaks <- function(xs, n = 100) {
  breaks <- quantile(xs, probs = seq(0, 1, length.out = n))
  breaks[!duplicated(breaks)]
}
toPlot_cooh_breaks <- quantile_breaks(assay(toPlot_cooh)[,1], n = 101)

mt <- toPlot_cooh[rownames(toPlot_cooh) %in% sig_diff_genes,]
# Labels to plot
    labels <- rownames(mt) 

    # Open a PNG device with a transparent background
ppi <- 300
png(file = "./plots/heatmap_cooh_by_sample.png", width = 6*ppi, height = 6*ppi, res = ppi, bg = "transparent")

heatmap_cooh <- pheatmap(assay(mt), 
                          cluster_rows=TRUE, 
                          cluster_cols=FALSE,
                          show_colnames = FALSE,
                          #show_rownames = FALSE,
                          annotation_col=df[c(2)], 
                          scale = "row", 
                          fontsize_row = 10, 
                          fontsize_col = 10, 
                          color = myheatcol,
                          #breaks = toPlot_cooh_breaks, 
                          angle_col = 315, 
                          main = "Carboxylic acid biosynthesis genes", 
                          cellheight = 10, cellwidth = 10,
                          labels_row = labels, 
                          #cutree_rows = 2,
                          gaps_col = c(8, 16)
                          )

dev.off()
heatmap_cooh

```


```{r print session info}
sessionInfo()
```